import { SHIR_CHALLENGE_TOKENS } from "../ShirChallenge.tokens";

export const ShirChallengeIngredientCardStyle = {
  root: {
    display: "flex",
    flexDirection: "column" as const,
    bgcolor: SHIR_CHALLENGE_TOKENS.peachSurface,
    border: "1px solid",
    borderColor: SHIR_CHALLENGE_TOKENS.peachChip,
    borderRadius: 3,
    p: { xs: 2.5, sm: 3 },
    mb: { xs: 3, sm: 4 },
  },
  header: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    mb: 1.5,
  },
  headerLabel: {
    color: SHIR_CHALLENGE_TOKENS.peachAccent,
    fontWeight: 700,
    letterSpacing: "0.06em",
    textTransform: "uppercase" as const,
    fontSize: "0.7rem",
  },
  monthChip: {
    display: "inline-block",
    bgcolor: SHIR_CHALLENGE_TOKENS.peachChip,
    color: SHIR_CHALLENGE_TOKENS.peachAccent,
    px: 1.5,
    py: 0.5,
    borderRadius: 2,
    typography: "caption",
    fontWeight: 600,
  },
  ingredientName: {
    fontWeight: 700,
    color: "text.primary",
    mb: 1,
  },
  description: {
    color: "text.secondary",
    mb: 2,
    lineHeight: 1.65,
  },
  statusChip: {
    display: "inline-block",
    bgcolor: "background.paper",
    border: "1px solid",
    borderColor: SHIR_CHALLENGE_TOKENS.peachChip,
    color: SHIR_CHALLENGE_TOKENS.peachAccent,
    px: 1.5,
    py: 0.5,
    borderRadius: 1.5,
    typography: "caption",
    fontWeight: 600,
    alignSelf: "flex-start",
  },
} as const;
