export const CollectionCardStyle = {
  card: {
    height: "100%",
    display: "flex",
    flexDirection: "column",
    borderRadius: 3,
    overflow: "hidden",
    transition: "box-shadow 200ms ease",
    "&:hover": {
      boxShadow: 6,
    },
  },
  actionArea: {
    flexGrow: 1,
    display: "flex",
    flexDirection: "column",
    alignItems: "stretch",
  },
  imageZone: {
    position: "relative",
    aspectRatio: "3 / 2",
    overflow: "hidden",
    bgcolor: "action.hover",
    flexShrink: 0,
  },
  image: {
    position: "absolute",
    inset: 0,
    width: "100%",
    height: "100%",
    objectFit: "cover",
  },
  imageFallback: {
    width: "100%",
    height: "100%",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
  },
  imageFallbackIcon: {
    fontSize: 64,
    color: "text.disabled",
    opacity: 0.4,
  },
  content: {
    flexGrow: 1,
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
    gap: 0.75,
    pt: 2,
    pb: "16px !important",
    px: 2,
  },
  title: {
    fontWeight: 700,
    textAlign: "center",
    lineHeight: 1.35,
    minHeight: "2.7em",
    display: "-webkit-box",
    WebkitLineClamp: 2,
    WebkitBoxOrient: "vertical",
    overflow: "hidden",
  },
} as const;
