export const CollectionCardStyle = {
  card: {
    height: "100%",
    display: "flex",
    flexDirection: "column",
    borderRadius: 3,
    overflow: "hidden",
    transition: "box-shadow 200ms ease, transform 200ms ease",
    "&:hover": {
      boxShadow: 6,
      transform: "translateY(-6px)",
    },
  },
  actionArea: {
    flexGrow: 1,
    display: "flex",
    flexDirection: "column",
    alignItems: "stretch",
  },
  imageZone: {
    position: "relative",
    aspectRatio: "3 / 2",
    overflow: "hidden",
    bgcolor: "action.hover",
    flexShrink: 0,
  },
  content: {
    flexGrow: 1,
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
    gap: 0.75,
    pt: 2,
    pb: "16px !important",
    px: 2,
  },
  title: {
    fontWeight: 700,
    textAlign: "center",
    lineHeight: 1.35,
    overflow: "hidden",
    width: "100%",
  },
} as const;
